name: deepwork # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: a command-line tool that help to focus on work #79 char long summary
description: |
  a command-line tool for measure how much time do you spend
  on deep work each day and block distracting websites.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  deepwork:
    # See 'snapcraft plugins'
    plugin: python
    python-packages:
      - docopt == 0.6.1
    source: .

apps:
  deepwork:
    command: deepwork.py
